[tool.poetry]
name = "fantacalcio-fastapi-mysql"
version = "0.1.0"
description = ""
authors = ["Valerio 'ftp21' Mancini <ftp21@ftp21.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
fastapi = "*"
typer = "*"
uvicorn = "*"
fastapi-sqlalchemy = "*"
sqlalchemy = "*"
pydantic = "*"
mysqlclient = "*"
typing = "*"
python-multipart = "*"
aiofiles = "*"
requests = "*"
python-dotenv = "*"
sqlalchemy-utils = "*"
websockets = "*"
fastapi-websocket-pubsub = "*"
fastapi-plugins = "*"
fastapi-socketio = "*"
beautifulsoup4 = "*"
pyyaml = "*"
xlsxwriter = "*"


[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = false
